# اسم الـ Workflow
name: Scrape Products and Deploy to GitHub Pages

# متى يتم تشغيل الـ Workflow (عند كل دفع push للفرع main)
on:
  push:
    branches:
      - main

# الصلاحيات المطلوبة للـ Workflow (تم التصحيح هنا)
permissions:
  contents: write # <-- هذا هو التعديل الأساسي
  pages: write
  id-token: write

# تعريف المهام (Jobs)
jobs:
  # مهمة البناء والنشر
  build-and-deploy:
    runs-on: ubuntu-latest # التشغيل على نظام Ubuntu

    steps:
      # الخطوة 1: سحب الكود من الريبو
      - name: Checkout repository
        uses: actions/checkout@v4

      # الخطوة 2: إعداد بيئة بايثون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # الخطوة 3: تثبيت المكتبات المطلوبة
      - name: Install dependencies
        run: pip install -r requirements.txt

      # الخطوة 4: تشغيل سكربت سحب البيانات
      - name: Run scraper
        run: python scraper.py

      # الخطوة 5: نشر الملفات إلى GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # النشر من المجلد الرئيسي (حيث يوجد index.html و products.json)
